#!/bin/bash -eu

assert() {
  echo -n "Testing $1 => $2: "
  test "$(clojure -M $1.clj)" == "$2" && echo OK || fail
}

fail() {
  echo FAIL
  exit 1
}

assert 01 "53974 52840"
assert 02 "2545 78111"
assert 03 "520019"
