#!/bin/bash -eu

t01() { assert 01 "53974 52840"; }
t02() { assert 02 "2545 78111"; }
t03() { assert 03 "520019 75519888"; } 
t04() { assert 04 "20667 5833065"; }
t05() { assert 05 "403695602"; }
t06() { assert 06 "32076"; }

assert() {
  echo -n "Testing $1 => $2: "
  test "$(clojure -M $1.clj)" == "$2" && echo OK || fail
}

fail() {
  echo FAIL
  exit 1
}

if [[ -n "${1:-}" ]]; then
  t$1
else
  for t in $(declare -f | grep "^t[0-9][0-9] () $" | sed 's/ .*//'); do
    $t
  done
fi
